parameters:
    # Adds a fallback DATABASE_URL if the env var is not set. This allows you
    # to run cache:warmup even if your environment variables are not available
    # yet. You should not need to change this value.
    env(DATABASE_DRIVER): 'pdo_sqlite'
    env(DATABASE_URL): ''

doctrine:
    dbal:
        charset: utf8mb4
        url: '%env(resolve:DATABASE_URL)%'

        # For SQLite
        # driver: 'pdo_sqlite'
        # server_version: '3.15'

        # For MySQL
        # driver: 'pdo_mysql'
        # server_version: 5.7	

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Bolt:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'Bolt\Entity'
                alias: App
        dql:
            string_functions:
                JSON_EXTRACT: Bolt\Doctrine\Functions\JsonExtract
                CAST: DoctrineExtensions\Query\Mysql\Cast
                INSTR: DoctrineExtensions\Query\Mysql\Instr
            numeric_functions:
                RAND: Bolt\Doctrine\Functions\Rand

