twig:
    debug: '%kernel.debug%'
    strict_variables: true
    form_themes:
        - 'form/layout.html.twig'
        - 'form/fields.html.twig'
    paths:
        '%kernel.project_dir%/public/theme/%bolt.theme%': ''
        '%kernel.project_dir%/templates/': 'bolt'
