twig:
    debug: '%kernel.debug%'
    strict_variables: true
    form_themes:
        - '@bolt/form/layout.html.twig'
        - '@bolt/form/fields.html.twig'
    paths:
        # Since the name of the theme folder is dynamic, we shouldn't set it here, but dynamically
        # See TwigAwareController::setTwigLoader()
        # '%kernel.project_dir%/public/theme/%bolt.theme%': ''
        '%kernel.project_dir%/templates/': 'bolt'
    globals:
        'config': '@Bolt\Configuration\Config'
