language: php
dist: trusty
sudo: false

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    # Pinned to 7.1.18, because Travis defaults to 7.1.6, which has broken SSL/TLS. See: https://github.com/travis-ci/travis-ci/issues/6339
    - php: 7.1.18
    - php: 7.1.18
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
    - php: 7.3
    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
  allow_failures:
    - php: nightly
    - php: 7.1.18
      env: COMPOSER_FLAGS="--prefer-lowest"

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer self-update -q

install:
  - COMPOSER_MEMORY_LIMIT=-1 composer update $COMPOSER_FLAGS
  - nvm install 12.5
  - npm ci
  - cd tests/e2e && npm ci && node ./node_modules/protractor/bin/webdriver-manager update --gecko=false && cd ../..

before_script:
  # build assets
  - npm run build
  # prepare web server for e2e tests
  - ./bin/console doctrine:database:create
  - ./bin/console doctrine:schema:create
  - ./bin/console doctrine:fixtures:load --group=without-images -n
  - ./bin/console server:start 127.0.0.1:8088
  # test if web server works
  - sleep 3
  - wget "http://127.0.0.1:8088/bolt/login"

script:
  # this checks that the source code follows the Bolt Code Syntax rules
  - ./vendor/bin/ecs check src
  - ./vendor/bin/phpstan analyse -c phpstan.neon src
  # this checks that the YAML config files contain no syntax errors
  - ./bin/console lint:yaml config
  # this checks that the Twig template files contain no syntax errors
  - ./bin/console lint:twig templates
  # this checks that the XLIFF translations contain no syntax errors
  - ./bin/console lint:xliff translations
  # this checks that the application doesn't use dependencies with known security vulnerabilities
  - ./bin/console security:check
  # this checks that the composer.json and composer.lock files are valid
  # - composer validate --strict # temporarily disabled bue to bug in api platform 2.4.0-beta.2
  # this checks that Doctrine's mapping configurations are valid
  - ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
  # run PHP Unit / PHP Spec tests
  - ./vendor/bin/phpspec run
  - ./vendor/bin/phpunit
  # run API tests
  - ./vendor/bin/behat
  # run e2e tests with Kakunin
  - cd tests/e2e && npm run kakunin && cd ../..
