# All route definitions, used by Bolt: Bolt Control Panel ("backend"), Async and
# Thumbs, unless overridden in `../routes.yaml` or another location.

# The Bolt Control Panel ("backend"). It's common to modify the `prefix` so the
# Control Panel can be accessed at a custom URL.
control_panel:
    resource: '../../src/Controller/Backend/'
    prefix: '%bolt.backend_url%'
    type: annotation

# Async: Upload, Embed
control_panel_async:
    resource: '../../src/Controller/Backend/Async/'
    prefix: '%bolt.backend_url%/async'
    type: annotation

# ImageController, Currently only used for thumbnails
controllers:
    resource: '../../src/Controller/ImageController.php'
    type: annotation

# Routes added by Extensions get added here, by Bolt\Extension\RoutesLoader
extensions:
    resource: .
    type: bolt_extensions
