# Note: Database setup is best done in ENV variables. See the file `.env`
# in the project root.

# The name of the website
sitename: Bolt Core Git Clone
payoff: The amazing payoff goes here

secret: '%env(APP_SECRET)%'

# Set the caching configuration for various areas of Bolt.
# The expires_after is counted in seconds.
#caching:
#    related_options: 3600
#    canonical: 1800
#    formatter: 180
#    selectoptions: 3600
#    content_array: 180
#    frontend_menu: 3600
#    backend_menu: 3600
#    files_index: 3600
#    list_format: true  # Run `bin/console cache:list-format; bin/console bolt:update-list-format` to clear and rebuild these

caching:
    related_options: ~
    canonical: ~
    formatter: ~
    selectoptions: ~
    content_array: ~
    frontend_menu: ~
    backend_menu: ~
    files_index: ~
    list_format: false # Run `bin/console cache:list-format; bin/console bolt:update-list-format` to clear and rebuild these

# The theme to use.
#
# Dont edit the provided templates directly, because they _will_ get updated
# in next releases. If you wish to modify a default theme, copy its folder, and
# change the name here accordingly.
theme: skeleton

# Set the timezone to be used on the website. For a list of valid timezone
# settings, see: http://php.net/manual/en/timezones.php
# timezone: UTC

# Set the default time format used on this website. For a list of valid date
# format settings, see: https://www.php.net/manual/en/function.date.php
date_format: 'F j, Y H:i'

# You can set a preference to omit background images on the login screen.
omit_backgrounds: true

# If you're a party-pooper who wants to hide the `generator` meta tag and
# `x-powered-by` header, set these to true
omit_meta_generator_tag: false

headers:
    # Allow of Google's FLoC by setting this to `true` (defaults to `false` for opt-out)
    # https://github.com/symfony/symfony/pull/40989
    allow-floc: false
    # Add Bolt's "Powered By" (defaults to `true`)
    powered_by: true

# If your site is reachable under different urls (say, both blog.example.org/
# as well as example.org/), its a good idea to set one of these as the
# canonical, so its clear which is the primary address of the site.
#
# If you include `https://`, it will be included in the canonical urls.
#canonical: https://example.org

# If you want to override the canonical template, from the theme:
#canonical_template: 'partials/_canonical.html.twig'

# If you want to add canonical link in your own way, set this to true
omit_canonical_link: false

# By setting this to true, you will get a relative canonical path passed to the template.
#relative_canonical_url: true

# Bolt can insert a <link rel="shortcut icon"> for all pages on the site.

# Note: The location given is relative to the currently selected theme. If
#       you want to set the icon yourself, just dont enable the following line.
#favicon: images/favicon-bolt.ico

# The default content to use for the homepage, and the template to render it
# with. This can either be a singleton like `homepage`, a specific record (like
# `page/1`) or a listing of records (like `entries`). In the chosen
# homepage_template, you will have `record` or `records` at your disposal,
# depending on the homepage setting.
#
# Note: If you've changed the filename, and your changes do not show up on
#       the website, be sure to check for a theme.yaml file in your themes
#       folder. If a template is set there, it will override the setting here.
homepage: homepage
homepage_template: index.twig

# The default content for the "Not Found" (404) page. Can be an (array of) template
# names or identifiers for records, which will be tried until a match is found.
notfound: [ blocks/404-not-found, 'helpers/page_404.html.twig' ]

# Toggle maintenance mode on or off. Note: If you're logged in, you'll still see
# the website as usual. Use an incognito window to see the "maintenance" page.
maintenance_mode: false

# The default for the "Maintenance mode" (503) page. Can be an (array of) template
# names or identifiers for records, which will be tried until a match is found.
maintenance: [ blocks/503-maintenance-mode, 'helpers/page_503.html.twig' ]

# The default content for the "Forbidden" (403) page. Can be an (array of) template
# names or identifiers for records, which will be tried until a match is found.
forbidden: [ blocks/403-forbidden, 'helpers/page_403.html.twig' ]

# The default content for the "Internal Server Error" (500) page. Can be an
# (array of) template names or identifiers for records.
# Note: Only used in `APP_ENV=prod` mode. You're advised to keep this as simple
# as possible, because if an error occurs in this template, it can not be
# handled, and you'll have a bad time debugging it!
internal_server_error: [ 'helpers/page_500.html.twig' ]

# The default template for record-pages on the site.
#
# Can be overridden for each content type and for each record, if it has a
# templateselect field.
#
# Note: If you've changed the filename, and your changes do not show up on the
#       website, be sure to check for a config.yaml file in your themes folder.
#       If a template is set there, it will override the setting here.
record_template: record.twig

# The default template and amount of records to use for listing-pages on the
# site.
#
# Can be overridden for each content type.
#
# Note: If you've changed the filename, and your changes do not show up on the
#         website, be sure to check for a config.yaml file in your themes
#         folder. If a template is set there, it will override the setting here.
listing_template: listing.twig
listing_records: 6
listing_sort: datepublish DESC

# Allow filtering on listing pages using query parameters, much like you would
# with {% setcontent %}. E.g. /pages?order=id and /pages?title--like=voluptat
# Useful for search.
query_search:
    # Enables filtering.
    enable: true
    # If true, query params with empty values will be ignored.
    ignore_empty: false

# Maximum amount of items to show in a `<select>` for picking a record. For
# example in `type: select`.
maximum_listing_select: 50000

# Template for showing the search results. If not defined, uses the settings for
# listing_template and listing_records.
#
# Note: If you've changed the filename, and your changes do not show up on the
#       website, be sure to check for a config.yaml file in your themes folder.
#       If a template is set there, it will override the setting here.
search_results_template: search.twig
search_results_records: 10

# The default amount of records to show on overview pages. Can be overridden
# for each content type.
records_per_page: 8

# Default settings for thumbnails.
#
# quality:       Quality should be between 0 (horrible, small file) and 100 (best, huge file).
# save_files:    Save files in the thumbs/ folder, so subsequent requests will serve file directly. Great for performance
#
# Note: If you change these values, you might need to clear the cache before
#       they show up.
thumbnails:
    default_thumbnail: [ 320, 240 ]
    default_image: [ 1000, 750 ]
    default_cropping: crop
    quality: 80
    save_files: true

# File permissions for read/write/execute to set on folders and files that are
# created. The exact permissions you should be setting depends on the system
# user that PHP (and/or your webserver) is running as, and the user who owns the
# actual folders/files.
#
# - If they are the same user, use `0o755` for folders and `0o644` for files.
# - If they're in the same group, use use `0o775` for folders and `0o664` for files.
# - If you don't know, or you can't make it work otherwise, then use `0o777` for folders and `0o666` for files.
filepermissions:
    folders: 0o775
    files: 0o664

# Define the HTML tags and attributes that are allowed in cleaned HTML. This
# is used for sanitizing HTML, to make sure there are no undesirable elements
# left in the content that is shown to users. For example, tags like `<script>`
# or `onclick`-attributes.
# Note: enabling options in the `wysiwyg` settings will implicitly add items to
# the allowed tags. For example, if you set `images: true`, the `<img>` tag
# will be allowed, regardless of it being in the `allowed_tags` setting.
htmlcleaner:
    allowed_tags: [ div, span, p, br, hr, s, u, strong, em, i, b, li, ul, ol, mark, blockquote, cite, pre, code, tt, h1, h2, h3, h4, h5, h6, dd, dl, dt, table, tbody, thead, tfoot, th, td, tr, a, img, address, abbr, iframe, caption, sub, sup, figure, figcaption, article, section, small ]
    allowed_attributes: [ id, class, style, name, value, href, src, alt, title, width, height, frameborder, allowfullscreen, scrolling, target, colspan, rowspan, rel, download, hreflang ]
    allowed_frame_targets: [ _blank, _self, _parent, _top ]

# Define the file types (extensions to be exact) that are acceptable for upload
# in either file fields or through the files screen.
accept_file_types: [ yaml, twig, html, js, css, scss, gif, jpg, jpeg, png, ico, zip, tgz, txt, md, doc, docx, pdf, epub, xls, xlsx, ppt, pptx, mp3, ogg, wav, m4a, mp4, m4v, ogv, wmv, avi, webm, svg, webp, avif]

# Alternatively, if you wish to limit these, uncomment the following list
# instead. It just includes file types / extensions that are harder to exploit.
# accept_file_types: [ gif, jpg, jpeg, png, txt, md, pdf, epub, mp3 ]

accept_media_types: [ gif, jpg, jpeg, png, svg, pdf, mp3, tiff, avif, webp ]

# Set the maximum upload size. Note, this can never exceed the settings for
#`post_max_size` and `upload_max_filesize` in `php.ini`.
accept_upload_size: 8M

# Default location for uploading files.
upload_location: "{contenttype}/{year}/{month}/"

# Options to use with curl requests.
# For all options, check the official curl documentation here https://curl.haxx.se/libcurl/c/curl_easy_setopt.html
curl_options:
    verify_peer: false

# Various settings about Bolt's built-in localization features.
localization:
    fallback_when_missing: true # When set to true, fields with empty values will fallback to the default locale's value.
    remove_default_locale_on_canonical: true # When set to true removes locale prefix on default locale canonical URLs

# Define the seed used to generated the test data
# Used in <bolt-core>/src/DataFixtures/ContentFixtures.php
fixtures_seed: 87654

# Globally enable / disable the validator for Fields
validator_options:
    enable: true

# Options for user's avatar
user_avatar:
    upload_path: avatars
    extensions_allowed: ['png', 'jpeg', 'jpg', 'gif']
    default_avatar: '' # Put path of file locate in files directory

# Settings for the reset password logic
reset_password_settings:
    show_already_requested_password_notice: true
    mail_from: "do-not-reply@example.org"
    mail_name: "Bolt CMS"
    mail_subject: "Your password reset request"
    mail_template: "reset_password/email.html.twig"

# Adds sorting and filtering of users in backend
user_show_sort&filter: true

# Use Ajaxy saving ("Stay on page"), or traditional saving
ajaxy_saving: false
