# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
    - label: Home
      title: This is the <b>first<b> menu item.
      link: homepage
      class: homepage
    - label: About
      link: blocks/about
      submenu:
          - label: Sub 1
            link: entry/29
          - label: Sub 2
            class: menu-item-class
            link: entry/30
          - label: Sub 3
            link: entry/31
          - label: Sub 4
            class: sub-class
            link: page/32
    - label: All pages
      link: pages/
    - label: The Bolt site
      link: https://bolt.cm
      class: bolt-site
      title: Visit the excellent Bolt website!
      
foo: bar